In [62]:
# import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

warnings.filterwarnings('ignore')

In [87]:
# URL's for test and train data
train_url = 'https://raw.githubusercontent.com/bksat90kc/KaggleChallenge/main/train.csv'
test_url = 'https://raw.githubusercontent.com/bksat90kc/KaggleChallenge/main/test.csv'

In [88]:
# read the train data
train_df = pd.read_csv(train_url)
train_df.drop('Name', axis=1, inplace=True)

PassengerId HomePlanet CryoSleep  Cabin  Destination   Age    VIP  \
0     0001_01     Europa     False  B/0/P  TRAPPIST-1e  39.0  False   
1     0002_01      Earth     False  F/0/S  TRAPPIST-1e  24.0  False   
2     0003_01     Europa     False  A/0/S  TRAPPIST-1e  58.0   True   
3     0003_02     Europa     False  A/0/S  TRAPPIST-1e  33.0  False   
4     0004_01      Earth     False  F/1/S  TRAPPIST-1e  16.0  False   

   RoomService  FoodCourt  ShoppingMall     Spa  VRDeck  Transported  
0          0.0        0.0           0.0     0.0     0.0        False  
1        109.0        9.0          25.0   549.0    44.0         True  
2         43.0     3576.0           0.0  6715.0    49.0        False  
3          0.0     1283.0         371.0  3329.0   193.0        False  
4        303.0       70.0         151.0   565.0     2.0         True

In [111]:
train_df.head()

PassengerId HomePlanet  CryoSleep  Cabin  Destination   Age  VIP  \
0     0001_01     Europa          0  B/0/P  TRAPPIST-1e  39.0    0   
1     0002_01      Earth          0  F/0/S  TRAPPIST-1e  24.0    0   
2     0003_01     Europa          0  A/0/S  TRAPPIST-1e  58.0    1   
3     0003_02     Europa          0  A/0/S  TRAPPIST-1e  33.0    0   
4     0004_01      Earth          0  F/1/S  TRAPPIST-1e  16.0    0   

   RoomService  FoodCourt  ShoppingMall     Spa  VRDeck  Transported  
0          0.0        0.0           0.0     0.0     0.0            0  
1        109.0        9.0          25.0   549.0    44.0            1  
2         43.0     3576.0           0.0  6715.0    49.0            0  
3          0.0     1283.0         371.0  3329.0   193.0            0  
4        303.0       70.0         151.0   565.0     2.0            1

In [110]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8693 entries, 0 to 8692
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   PassengerId   8693 non-null   object 
 1   HomePlanet    8693 non-null   object 
 2   CryoSleep     8693 non-null   int64  
 3   Cabin         8494 non-null   object 
 4   Destination   8693 non-null   object 
 5   Age           8514 non-null   float64
 6   VIP           8693 non-null   int64  
 7   RoomService   8512 non-null   float64
 8   FoodCourt     8510 non-null   float64
 9   ShoppingMall  8485 non-null   float64
 10  Spa           8510 non-null   float64
 11  VRDeck        8505 non-null   float64
 12  Transported   8693 non-null   int64  
dtypes: float64(6), int64(3), object(4)
memory usage: 883.0+ KB


In [105]:
train_df.HomePlanet.unique()

array(['Europa', 'Earth', 'Mars', 'unknown'], dtype=object)

In [103]:
train_df.CryoSleep.unique()

array([0, 1], dtype=object)

In [104]:
train_df.Destination.unique()

array(['TRAPPIST-1e', 'PSO J318.5-22', '55 Cancri e', 'unknown'],
      dtype=object)

In [107]:
train_df.VIP.unique()

array([0, 1])

In [108]:
train_df.Transported.unique()

array([0, 1], dtype=object)

In [85]:
# train_df['CryoSleep'] = train_df['CryoSleep'].astype('bool')

In [95]:
# replace NaN values in dataframe
values = {'HomePlanet': 'unknown', 'CryoSleep': 'False', 'Destination': 'unknown', 'VIP': 'False'}
train_df.fillna(value=values, inplace=True)

In [96]:
# convert Transported column to numeric values : 0 for False and 1 for True
train_df.loc[train_df["Transported"] == False, "Transported"] = 0
train_df.loc[train_df["Transported"] == True, "Transported"] = 1

In [100]:
# convert VIP column to numeric values : 0 for False and 1 for True
train_df.loc[train_df["VIP"] == False, "VIP"] = 0
train_df.loc[train_df["VIP"] == 'False', "VIP"] = 0
train_df.loc[train_df["VIP"] == True, "VIP"] = 1

In [102]:
# convert CryoSleep column to numeric values : 0 for False and 1 for True
train_df.loc[train_df["CryoSleep"] == False, "CryoSleep"] = 0
train_df.loc[train_df["CryoSleep"] == 'False', "CryoSleep"] = 0
train_df.loc[train_df["CryoSleep"] == True, "CryoSleep"] = 1

In [109]:
# convert the data type to integer
train_df['Transported'] = train_df['Transported'].astype('int64')
train_df['CryoSleep'] = train_df['CryoSleep'].astype('int64')
train_df['VIP'] = train_df['VIP'].astype('int64')

In [4]:
# read the train data
test_df = pd.read_csv(test_url)
test_df.head()

PassengerId HomePlanet CryoSleep  Cabin  Destination   Age    VIP  \
0     0013_01      Earth      True  G/3/S  TRAPPIST-1e  27.0  False   
1     0018_01      Earth     False  F/4/S  TRAPPIST-1e  19.0  False   
2     0019_01     Europa      True  C/0/S  55 Cancri e  31.0  False   
3     0021_01     Europa     False  C/1/S  TRAPPIST-1e  38.0  False   
4     0023_01      Earth     False  F/5/S  TRAPPIST-1e  20.0  False   

   RoomService  FoodCourt  ShoppingMall     Spa  VRDeck              Name  
0          0.0        0.0           0.0     0.0     0.0   Nelly Carsoning  
1          0.0        9.0           0.0  2823.0     0.0    Lerome Peckers  
2          0.0        0.0           0.0     0.0     0.0   Sabih Unhearfus  
3          0.0     6652.0           0.0   181.0   585.0  Meratz Caltilter  
4         10.0        0.0         635.0     0.0     0.0   Brence Harperez

In [14]:
# extract required train data
X = train_df.drop('Transported', axis=1)
y = train_df[['Transported']]

In [21]:
# split the data
X_train, X_valid, y_train, y_valid = train_test_split(X, y, test_size=0.33, random_state=2)

In [22]:
# logistic regression
clobj = LogisticRegression()
clobj.fit(X_train, y_train)

ValueError: could not convert string to float: 'Europa'